--DESTRUCCION DE TABLAS
DROP TABLE AparatoAuditivo
DROP TABLE AreaTrabajo
DROP TABLE Causa
DROP TABLE Causado
DROP TABLE Censo
DROP TABLE Colonia
DROP TABLE Delegacion
DROP TABLE Empleo
DROP TABLE EsGrado
DROP TABLE Estado
DROP TABLE EstadoCivil
DROP TABLE Estudiado
DROP TABLE Gana
DROP TABLE Grado
DROP TABLE Hijo
DROP TABLE IncluyePrivilegio
DROP TABLE InstitucionEducativa
DROP TABLE LenguaDominante
DROP TABLE LocalizaEmpleo
DROP TABLE LocalizaInstitucionEducativa
DROP TABLE Marca
DROP TABLE Municipio
DROP TABLE NivelEducativo
DROP TABLE NivelEspanol
DROP TABLE NivelIngles
DROP TABLE NivelLSM
DROP TABLE PerdidaAuditiva
DROP TABLE Periodo
DROP TABLE Persona
DROP TABLE PerteneceCenso
DROP TABLE Privilegio
DROP TABLE PoseeAparatoAuditivo
DROP TABLE Rol
DROP TABLE Sueldo
DROP TABLE TieneEmpleo
DROP TABLE TieneEstadoCivil
DROP TABLE TieneLenguaDominante
DROP TABLE TieneNivelEducativo
DROP TABLE TieneNivelEspanol
DROP TABLE TieneNivelIngles
DROP TABLE TieneNivelLSM
DROP TABLE TienePerdidaAuditiva
DROP TABLE TieneRol
DROP TABLE Usuario
DROP TABLE Vive