-- CARGA DE DATOS

-- Carga de PERIODO

LOAD DATA INFILE 'periodo.csv'
INTO TABLE pruebacseq.periodo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga PERSONA
LOAD DATA INFILE 'Persona.csv'
INTO TABLE pruebacseq.persona
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga de ESTADO

LOAD DATA INFILE 'Estado.csv'
INTO TABLE pruebacseq.estado
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- carga de INSTITUCIONEDUCATIVA

LOAD DATA INFILE 'InstitucionEducativa.csv'
INTO TABLE pruebacseq.institucioneducativa
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga LENGUADOMINANTE

LOAD DATA INFILE 'LenguaDominante.csv'
INTO TABLE pruebacseq.lenguadominante
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga NIVELINGLES

LOAD DATA INFILE 'NivelIngles.csv'
INTO TABLE pruebacseq.nivelingles
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga NIVELESPANOL

LOAD DATA INFILE 'NivelEspanol.csv'
INTO TABLE pruebacseq.nivelespanol
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga NIVELLSM

LOAD DATA INFILE 'NivelLSM.csv'
INTO TABLE pruebacseq.nivellsm
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga ESTADOCIVIL

LOAD DATA INFILE 'EstadoCivil.csv'
INTO TABLE pruebacseq.estadocivil
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga CENSO

LOAD DATA INFILE 'Censo.csv'
INTO TABLE pruebacseq.censo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga MARCA

LOAD DATA INFILE 'Marca.csv'
INTO TABLE pruebacseq.marca
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga HIJO

LOAD DATA INFILE 'Hijo.csv'
INTO TABLE pruebacseq.hijo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga GRADO

LOAD DATA INFILE 'Grado.csv'
INTO TABLE pruebacseq.grado
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga CAUSA

LOAD DATA INFILE 'Causa.csv'
INTO TABLE pruebacseq.causa
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga SUELDO

LOAD DATA INFILE 'Sueldo.csv'
INTO TABLE pruebacseq.sueldo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga AREATRABAJO

LOAD DATA INFILE 'AreaTrabajo.csv'
INTO TABLE pruebacseq.areatrabajo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga MUNICIPIO

LOAD DATA INFILE 'Municipio.csv'
INTO TABLE pruebacseq.municipio
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga DELEGACION

LOAD DATA INFILE 'Delegacion.csv'
INTO TABLE pruebacseq.delegacion
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga COLONIA

LOAD DATA INFILE 'Colonia.csv'
INTO TABLE pruebacseq.colonia
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga Vive

LOAD DATA INFILE 'Vive.csv'
INTO TABLE pruebacseq.vive
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga LOCALIZAINSTITUCIONEDUCATIVA

LOAD DATA INFILE 'LocalizaInstitucionEducativa.csv'
INTO TABLE pruebacseq.localizainstitucioneducativa
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga NIVELEDUCATIVO

LOAD DATA INFILE 'NivelEducativo.csv'
INTO TABLE pruebascseq.niveleducativo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga ESTUDIADO
LOAD DATA INFILE 'Estudiado.csv'
INTO TABLE pruebacseq.estudiado
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENENIVELEDUCATIVO
LOAD DATA INFILE 'TieneNivelEducativo.csv'
INTO TABLE pruebacseq.tieneniveleducativo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;
	

-- Carga TIENELENGUADOMINANTE
LOAD DATA INFILE 'TieneLenguaDominante.csv'
INTO TABLE pruebacseq.tienelenguadominante
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENENIVELINLGES
LOAD DATA INFILE 'TieneNivelIngles.csv'
INTO TABLE pruebacseq.tienenivelingles
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENENIVELESPANOL
LOAD DATA INFILE 'TieneNivelEspanol.csv'
INTO TABLE pruebacseq.tienenivelespanol
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENENIVELLSM
LOAD DATA INFILE 'TieneNivelLSM.csv'
INTO TABLE pruebacseq.tienenivellsm
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENEESTADOCIVIL
LOAD DATA INFILE 'TieneEstadoCivil.csv'
INTO TABLE pruebacseq.tieneestadocivil
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga PERTENECECENSO
LOAD DATA INFILE 'PerteneceCenso.csv'
INTO TABLE pruebacseq.pertenececenso
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga APARATOAUDITIVO
LOAD DATA INFILE 'AparatoAuditivo.csv'
INTO TABLE pruebacseq.aparatoauditivo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga POSEEAPARATOAUDITIVO
LOAD DATA INFILE 'PoseeAparatoAuditivo.csv'
INTO TABLE pruebacseq.poseeaparatoauditivo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;
	

-- Carga PERIDAAUDITIVA	
LOAD DATA INFILE 'PerdidaAuditiva.csv'
INTO TABLE pruebacseq.perdidaauditiva
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga CAUSADO
LOAD DATA INFILE 'Causado.csv'
INTO TABLE pruebacseq.causado
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga ESGRADO	
LOAD DATA INFILE 'EsGrado.csv'
INTO TABLE pruebacseq.EsGrado
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENEPERDIDAAUDITIVA
LOAD DATA INFILE 'TienePerdidaAuditiva.csv'
INTO TABLE pruebacseq.tieneperdidaauditiva
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga EMPLEO
LOAD DATA INFILE 'Empleo.csv'
INTO TABLE pruebacseq.empleo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

 -- Carga GANA
 
LOAD DATA INFILE 'Gana.csv'
INTO TABLE pruebacseq.gana
FIELDS TERMINATED BY ','
IGNORE 1 LINES;
	

-- Carga TIENEEMPLEO

LOAD DATA INFILE 'TieneEmpleo.csv'
INTO TABLE pruebacseq.tieneempleo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga LOCALIZAEMPLEO

LOAD DATA INFILE 'LocalizaEmpleo.csv'
INTO TABLE pruebacseq.localizaempleo
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- SECCION DE ROLES
-- Carga USUARIO

LOAD DATA INFILE 'Usuario.csv'
INTO TABLE pruebacseq.usuario
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga ROL

LOAD DATA INFILE 'Roles.csv'
INTO TABLE pruebacseq.rol
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga PRIVILEGIO

LOAD DATA INFILE 'Privilegio.csv'
INTO TABLE pruebacseq.pr
FIELDS TERMINATED BY ','
IGNORE 1 LINES;


-- Carga TIENEROL

LOAD DATA INFILE 'TieneRol.csv'
INTO TABLE pruebacseq.tienerol
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

-- Carga INCLUYEPRIVILEGIO

LOAD DATA INFILE 'IncluyePrivilegio.csv'
INTO TABLE pruebacseq.incluyeprivilegio
FIELDS TERMINATED BY ','
IGNORE 1 LINES;



